#!/bin/bash
set -e

# See https://github.com/bylexus/docker-apache-php55/blob/master/run
# see https://github.com/kojiromike/docker-magento/blob/master/apache/start_safe_perms



PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL & ~E_DEPRECATED"}
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php5/apache2/php.ini
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php5/cli/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php5/apache2/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php5/cli/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php5/apache2/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php5/cli/php.ini

create_user_from_directory_owner() {
    if [ $# -ne 1 ]; then
        echo "Creates a user (and group) from the owner of a given directory, if it doesn't exist."
        echo "Usage: create_user_from_directory_owner <path>"

        return 1
    fi

    local owner group owner_id group_id path
    path=$1

    read owner group owner_id group_id < <(stat -c '%U %G %u %g' $path)
    if [[ $owner = UNKNOWN ]]; then
        owner=hostuser
        if [[ $group = UNKNOWN ]]; then
            group=$owner
            addgroup --system --gid "$group_id" "$group" > /dev/null
        fi
        adduser --no-create-home --system --uid=$owner_id --gid=$group_id "$owner" > /dev/null
        echo "[Apache User] Created user for uid ($owner_id), and named it '$owner'"
    fi

    # Ensures the user apache is run at is the same as the project folder
    tmp=/tmp/$RANDOM
    {
        echo "User $owner"              
        echo "Group $group"             
        grep -v '^User' /etc/apache2/apache2.conf |
            grep -v '^Group'
    } >> "$tmp" &&
    cat "$tmp" > /etc/apache2/apache2.conf &&
    rm "$tmp"

    # Not volumes, so need to be chowned                
    chown -R "$owner:$group" /var/{lock,log,run}/apache*
    chown -R "$owner:$group" /var/www/dynamic


    export APACHE_RUN_USER=$owner
    export APACHE_RUN_GROUP=$group
    echo "[Apache User] Set APACHE_RUN_USER to $owner and APACHE_RUN_GROUP to $group"

    return 0
}

# Set Apache user/group
create_user_from_directory_owner "${VOLUME_PATH}"

# Copy .ssh keys (Windows support)
#   This is to ensure the keys are synced from the host PC
#   *and* that the permissions can be changed to avoid an error
#   when using Phing/Composer
#cp /root/.ssh/keys/id_rsa /root/.ssh/id_rsa
#cp /root/.ssh/keys/id_rsa.pub /root/.ssh/id_rsa.pub
#chmod 600 /root/.ssh/id_rsa
#chmod 600 /root/.ssh/id_rsa.pub

source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND